### ISSUE TITLE
移動端界面顯示問題

### ISSUE THREAD

**Issue by KagurazakaIzumi** [AyakaLab/ArcLight#135]
![photo_2020-09-25_22-24-14](https://user-images.githubusercontent.com/26840041/94279063-31854080-ff7e-11ea-8e9e-54f166f33fa3.jpg)
詳情查看圖片
具體問題：
1.標題欄寬度異常
2.底部 Copyright 行位置異常
設備信息：
型號：iPhone Xs
作業系統：iOS 14.0.1
瀏覽器版本：Safari 14

**Comment by KagurazakaIzumi** [comment]
此問題在“音樂上傳界面，關於界面，首頁”三個頁面不存在

**Comment by nekomeowww** [comment]
Fixed in #188
